### ISSUE TITLE
Heatblock section needs a quick check.

### ISSUE THREAD

**Issue by bassamanator** [bassamanator/everything-sovol-sv06#11]
@azhizhinov Please check heatblock section for errors, if at all possible. Thanks!

**Comment by azhizhinov** [comment]
Hello.
Hm, it's might be 14mm, I can't be 100% sure.
When an ordered one from Aliexpress will come, I will be able to compare.
Anyway, 1mm is in standard China inaccuracy.
Will see.
Should I remove this picture and alt text?
