### ISSUE TITLE
[INCORRECT SPECIFICATION] The connectors listed as JST 1.25mm are actually Molex PicoBlade

### ISSUE THREAD

**Issue by rmcardle** [bassamanator/everything-sovol-sv06#46]
Molex PicoBlade connectors and clones are commonly misidentified as JST 1.25mm connectors. JST does not make any connectors like this in this pitch. The closest they make are JST GH but those have a locking clip and a very different connection design.

See the Molex PicoBlade technical drawings here: https://www.molex.com/content/dam/molex/molex-dot-com/products/automated/en-us/salesdrawingpdf/510/51021/510210200_sd.pdf?inline

**What section:**
Hotend PCB, Heatblock Thermistor, Filament Sensor Cable How-To

**What part:**
All connectors listed as "JST 1.25mm"

**What is the correct specification:**
Molex PicoBlade

**Comment by bassamanator** [comment]
Thanks for this! Will look into it shortly.

**Comment by Docs-ITmatic** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
RJ45mp, @minty-E, @yangfan6888, @neosun100, @hudsonsouzalp, @com03240, @bakabakaba, @sgsgsgg, @Fonsori, @Kkkkrkkkkk, @StefanPengs, @DrOctavius, @DungntVccorp, @RobWei, @mrgluek, @GasComIT, @qudoosjutt, @comminutus, @HAOYUatHZ, @Leekeey

**Comment by bassamanator** [comment]
@rmcardle I've changed all mentions of `JST 1.25mm` to `Molex PicoBlade`. Feel free to report other errors.

Thanks! 🙏🏼
