### ISSUE TITLE
New Fix For Klipper Timezone

### ISSUE THREAD

**Issue by JamesHabben** [bassamanator/everything-sovol-sv06#49]
Hi, I created a fix for the timezone issue on the Sovol Klipper screens. It is here if you would like to link to it.

https://github.com/JamesHabben/SovolStuff

**Comment by bassamanator** [comment]
I created a discussion related to the sovol klipper screen [here](https://github.com/bassamanator/Sovol-SV06-firmware/discussions/173). Can you please post this there?

Thanks!
